Develop/develop/ARCloud
Banuba/quickstart-ios-swift pull request #7
Opened 2021-02-05 14:17 UTC by ve-sdk-ios

2021-02-08 14:33 UTC, GlebPBanuba reviewed
PR гуд! оказался даже на первый взгляд меньше чем в Android, но нужно сделать более читаемым для клиентов

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +import UIKit
а я правильно понимаю что название папки "AR Cloud" с пробелом?

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +        _ = sdkManager.loadEffect("UnluckyWitch", synchronous: true)
а зачем мы грузим эту маску на старте?

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func loadEffect(newEffectName: String) {
а этот метод загружает уже скачанный эффект с клауда?

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func loadEffectThumbs() {
Если это метод который скачивает превью, то лучше назвать
loadAREffectPreviewIcon

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func setUpRenderSize() {
А что это за код и как он относится к  AR Cloud?

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/AR Cloud/AREffectModel.swift
> +    var previewImage: String
previewImage - это путь к картинке?

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +    fileprivate static let banubaARCloud = BanubaARCloud(uuidString: cloudMasksToken)
cloudMasksToken -> clientCloudId

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +struct ARCloudManager {
а почему этот файл не лежит как и другие в "AR Cloud"?

2021-02-08 14:33 UTC, GlebPBanuba commented on quickstart-ios-swift/Managers/DataManager/EffectDataProvider.swift
> +extension EffectDataProvider: UICollectionViewDataSource {
А что делает этот класс?

2021-02-08 14:39 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +import UIKit
Исправил, спасибо!

2021-02-08 14:41 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +        _ = sdkManager.loadEffect("UnluckyWitch", synchronous: true)
Делал по аналогии с реализацией для камеры, можно убрать и добавить подсказку типа "Нажмите на эффект внизу" либо просто убрать и ничего не добавлять.

2021-02-08 14:44 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func loadEffect(newEffectName: String) {
метод возвращает эффект, который загружается в effectPlayer

2021-02-08 14:45 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func loadEffectThumbs() {
все верно, поменял

2021-02-08 15:12 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/DataManager/EffectDataProvider.swift
> +extension EffectDataProvider: UICollectionViewDataSource {
Cодержит настройки того - как и что будет отображаться в UICollectionView, а так же что будет происходить при взаимодействии с пользователем. Используется для выноса этой логики из нашего ARCloudViewController.

2021-02-08 15:19 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +    fileprivate static let banubaARCloud = BanubaARCloud(uuidString: cloudMasksToken)
+

2021-02-08 15:22 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +struct ARCloudManager {
Сетевые запросы вынес в отдельную сущность.

2021-02-08 15:27 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/AREffectModel.swift
> +    var previewImage: String
да, переименовал на previewImageStringUrl

2021-02-08 15:32 UTC, sdk-banuba requested changes

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/AppDelegate.swift
> +            resourcePath: [Bundle.main.bundlePath + "/effects", deviceDocumentsPath! + "/Effects/"],
Может вторую папку тоже с маленькой? "effects"?

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/Managers/DataManager/EffectDataManager.swift
> +//  Copyright © 2021 Ivan Gulidov. All rights reserved.
Я думаю, все эти копирайты поубирать нужно

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/BanubaClientToken.swift
> +internal let cloudMasksToken =  <#Place your token here#>
Собтвенно, я поэтому и хотел отдельный пример. Сейчас, чтобы запустить quickstart, нужен ещё какой-то cloudMasksToken. Сбивает с панталыку тех, кто просто хочет посмотреть "масочку"

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
README ещё нужно обновить

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private let config = EffectPlayerConfiguration(renderMode: .video)
Надо бы добавить renderContentMode аспект филл
private let config = EffectPlayerConfiguration(renderMode: .video, renderContentMode: .resizeAspectFill)
И из viewDidLoad можно удалить effectView.layoutIfNeeded()
Другим клиентам пригодится

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func loadEffect(newEffectName: String) {
Добавь ещё Bool для синхронной или асинхронной загрузки и можно его вызвать в viewWillAppear вместо 
_ = sdkManager.loadEffect.......

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateEffect), name: Notification.Name.newEffectDidLoad, object: nil)
Можешь строку разбить чтобы не была такой длинной? Удобнее читать

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +        NotificationCenter.default.removeObserver(self, name: Notification.Name.newEffectDidLoad, object: nil)
Тут тоже

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/AR Cloud/AREffectModel.swift
> +
Убрать копирайты

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/AR Cloud/EffectCollectionViewCell.swift
> +
Убрать копирайты

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/BanubaClientToken.swift
> +internal let cloudMasksToken =  <#Place your token here#>
Если запускается отдельной кнопкой пример то надо убрать placeholder чтобы проект компилился. Если токена нет нужного может alert какой сделать или проверку

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +
Убрать копирайт

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +                        banubaARCloud.downloadArEffect(effect) {(progress) in
Если fetchAREffects то давай и downloadAREffect

2021-02-08 15:32 UTC, sdk-banuba commented on quickstart-ios-swift/Managers/DataManager/EffectDataProvider.swift
> +                image = imageData != nil ? UIImage(data: imageData!) : UIImage()
Давай может без форс анрапов

2021-02-08 15:38 UTC, sdk-banuba commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func setUpRenderSize() {
setUpRenderSize() нужен для ротаций, он из примера. Ротации включены для всего проекта

2021-02-08 15:40 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func setUpRenderSize() {
setUpRenderSize() сетает конфиг EffectPlayer'a для рендеринга эффекта в зависимости от мода экрана (положения при вращении например)

2021-02-08 15:48 UTC, ve-sdk-ios commented on quickstart-ios-swift/AppDelegate.swift
> +            resourcePath: [Bundle.main.bundlePath + "/effects", deviceDocumentsPath! + "/Effects/"],
Комплишен метода downloadArEffect из BanubaARCloudSDK отдает мне урл типа file:///var/mobile/Containers/Data/Application/EEC9D64D-12A2-4BE7-AEAE-5980D0511A33/Documents/Effects/HairGradient_Cherry/. Я не могу поменять на "effects" так как будут разные пути к эффектам и они не загрузятся.

2021-02-08 15:49 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/DataManager/EffectDataManager.swift
> +//  Copyright © 2021 Ivan Gulidov. All rights reserved.
убрал

2021-02-08 15:51 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/AREffectModel.swift
> +
убрал

2021-02-08 15:51 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/EffectCollectionViewCell.swift
> +
убрал

2021-02-08 15:51 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +
убрал

2021-02-08 16:07 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateEffect), name: Notification.Name.newEffectDidLoad, object: nil)
исправил

2021-02-08 16:07 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +        NotificationCenter.default.removeObserver(self, name: Notification.Name.newEffectDidLoad, object: nil)
исправил

2021-02-08 16:24 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/DataManager/EffectDataProvider.swift
> +                image = imageData != nil ? UIImage(data: imageData!) : UIImage()
убрал

2021-02-08 21:21 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +                        banubaARCloud.downloadArEffect(effect) {(progress) in
исправил

2021-02-08 21:37 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private let config = EffectPlayerConfiguration(renderMode: .video)
renderContentMode: .resizeAspectFill - добавил, effectView.layoutIfNeeded() - оставил

2021-02-08 21:39 UTC, ve-sdk-ios commented on quickstart-ios-swift/AR Cloud/ARCloudViewController.swift
> +    private func loadEffect(newEffectName: String) {
Добавил

2021-02-09 06:47 UTC, bnb-itumashyk commented on quickstart-ios-swift/AppDelegate.swift
> +            resourcePath: [Bundle.main.bundlePath + "/effects", deviceDocumentsPath! + "/Effects/"],
Интересно, это важно будет отразить в докумпентации

2021-02-09 07:09 UTC, ve-sdk-ios commented on quickstart-ios-swift/BanubaClientToken.swift
> +internal let cloudMasksToken =  <#Place your token here#>
убрал placeholder, добавил алерт, который появляется в ARCloudViewController если clientCloudId пустой

2021-02-09 08:24 UTC, ve-sdk-ios commented on quickstart-ios-swift/AppDelegate.swift
> +            resourcePath: [Bundle.main.bundlePath + "/effects", deviceDocumentsPath! + "/Effects/"],
```
Лушче использовать это поле из ARCloudSDK. В следуюзем релизе сделаем поле статическим

@objc public class BanubaARCloud: NSObject {
  /// Storing path to the folder witch storing downloaded effects
  @objc public var effectsFolderURL: URL {
```

2021-02-09 09:12 UTC, ve-sdk-ios commented on quickstart-ios-swift.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
обновил, в отдельном пр

2021-02-09 09:31 UTC, bnb-ashershen commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +struct ARCloudManager {
лучше чтобы все что AR* в одном месте лежало

2021-02-09 16:08 UTC, GlebPBanuba commented on quickstart-ios-swift.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
https://github.com/Banuba/quickstart-ios-swift/pull/8?

2021-02-09 16:08 UTC, GlebPBanuba commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +class ARCloudViewController: UIViewController {
Какие строчки и блоки кода специфичны для AR Cloud?
Спрашиваю, потому что в такой простыне вызовов очень сложно глазу найти специфичные кусочки кода относящиеся к интеграции. 
Мое предложение перед вызовом метода добавить маленький комментарий.
Например, 
// Start loading all effect previews from AR Cloud
loadAREffectPreviewIcon()

а методы целиком относящиеся только для AR Cloud поднять выше по коду(можно еще добавить 
==== AR Cloud specific ====), а сопроводительный код по камере который есть и в других сэмплах опустить.

Это все делается чтобы клиенты меньше тратили времени на разбор и быстрее могли переносить такие куски кода и понимать что изменилось

2021-02-09 16:08 UTC, GlebPBanuba commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +extension ARCloudViewController {
а почему называется ARCloudViewController ведь не наследует ViewController?
это какая то специфика iOS так именовать
можно как то типа ARCloudViewControllerExtension?

2021-02-09 16:08 UTC, GlebPBanuba commented on quickstart-ios-swift/ARCloud/AREffectModel.swift
> +    var previewImageStringUrl: String
не помню как просил но лучше тогда
previewImageUrlString - так как тип String
или проще
previewUrlString
или даже
previewUrl

2021-02-09 16:08 UTC, GlebPBanuba commented on quickstart-ios-swift/BanubaClientToken.swift
> +internal let clientCloudId =  ""
давай без констант в сэмпле чтобы не искать их потом.

2021-02-09 16:08 UTC, GlebPBanuba commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +struct ARCloudManager {
Да, лучше все по сэмплу в одном месте. Для тех кто изучает сэмпл им важно картину видеть сразу

2021-02-09 16:08 UTC, GlebPBanuba commented on quickstart-ios-swift/Managers/DataManager/EffectDataProvider.swift
> +extension EffectDataProvider: UICollectionViewDataSource {
Это UI штука и к AR не относится?

2021-02-10 11:16 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/ARCloudManager/ARCloudManager.swift
> +struct ARCloudManager {
перенёс в ARCloud

2021-02-10 11:57 UTC, ve-sdk-ios commented on quickstart-ios-swift/Managers/DataManager/EffectDataProvider.swift
> +extension EffectDataProvider: UICollectionViewDataSource {
Относится, убрал ARCloudManager, все по коллекции перенес во вьюконтроллер.

2021-02-10 11:57 UTC, ve-sdk-ios commented on quickstart-ios-swift.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
да

2021-02-10 12:24 UTC, ve-sdk-ios commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +extension ARCloudViewController {
в iOS вьюконтроллер наследуется от UIViewController. В данном примере мы расширяем наш ARCloudViewController, для реализации этого в iOS есть семантика типа extension + объект, который расширяем.  "можно как то типа ARCloudViewControllerExtension?" - в данном случае нельзя, так как нет такого файла ARCloudViewControllerExtension. По неймингу - нет четких правил, но я стараюсь вьюконтроллеры называть так: первая часть отражает за что отвечает +ViewController, например если отвечает за работу с профилем юзера -  то ProfileViewController.

2021-02-10 12:35 UTC, ve-sdk-ios commented on quickstart-ios-swift/BanubaClientToken.swift
> +internal let clientCloudId =  ""
Перенес в ARCloud, нужна для алерта, а так можно было летать сразу в BanubaARCloud(uuidString:

2021-02-10 12:37 UTC, ve-sdk-ios commented on quickstart-ios-swift/ARCloud/AREffectModel.swift
> +    var previewImageStringUrl: String
previewUrl

2021-02-10 13:06 UTC, ve-sdk-ios commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +class ARCloudViewController: UIViewController {
Код по ARCloud поднял, добавил комменты к основным методам

2021-02-11 15:21 UTC, GlebPBanuba commented on quickstart-ios-swift.xcodeproj/project.pbxproj
>  /* Begin PBXBuildFile section */
Давай сразу все в одной задаче, а то сейчас 8й пр уйдет раньше этого пра.
В #8 не так уж и много изменений

2021-02-11 15:21 UTC, GlebPBanuba commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +    // Show alert if Client Cloud Id is empty in ARCloudManager/clientCloudId
укажи пожалуйста конкретное название константы вместо "Client Cloud Id" так всегда будет понятнее
а еще лучше Class.variable - 100% что будет понятно с первого раза что требуется от клиента

2021-02-11 15:21 UTC, GlebPBanuba commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +        guard ARCloudManager.clientCloudId != "" else {
а я правильно понимаю что будет краш если если не указал clientId?

2021-02-11 15:33 UTC, ve-sdk-ios commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +        guard ARCloudManager.clientCloudId != "" else {
нет, краша не будет, так как clientCloudId = ""

2021-02-11 15:38 UTC, ve-sdk-ios commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +    // Show alert if Client Cloud Id is empty in ARCloudManager/clientCloudId
поправил на // Show alert if ARCloudManager.clientCloudId is empty

2021-02-11 18:56 UTC, GlebPBanuba commented on README.md
> + 1. Get the latest BanubaARCloud SDK archive for iOS and the client CloudId. Please fill in our form on [form on banuba.com](https://www.banuba.com/face-filters-sdk) website, or contact us via [info@
Игорь, какой текст здесь лучше написать?

2021-02-12 11:16 UTC, bnb-itumashyk approved these changes

2021-02-12 11:16 UTC, bnb-itumashyk commented on README.md
> + 1. Get the latest BanubaARCloud SDK archive for iOS and the client CloudId. Please fill in our form on [form on banuba.com](https://www.banuba.com/face-filters-sdk) website, or contact us via [info@
Get the latest Banuba and BanubaARCloud SDKs archives for iOS and the client CloudId and token. Please fill in our form on [form on banuba.com](https://www.banuba.com/face-filters-sdk) website, or contact us via [info@banuba.com](mailto:info@banuba.com).

2021-02-12 12:55 UTC, bnb-ashershen commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
почему не viewWillDisappear?

2021-02-12 12:55 UTC, bnb-ashershen commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +        sdkManager.removeRenderTarget()
лучше дергать sdkManager.destroyEffectPlayer() он внутри сам удалит рендер таргет

2021-02-12 12:56 UTC, bnb-ashershen commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +        sdkManager.setup(configuration: config)
лучше это перенести в viewDidAppear() чтобы жизненный цикл эффект плеера полностью совпадал с жизненным циклом вьюхи

2021-02-12 14:43 UTC, bnb-ashershen commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +        setUpRenderTarget()
неочевидно что setUpRenderSize вызывает setUpRenderTarget

2021-02-12 14:43 UTC, bnb-ashershen commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +        sdkManager.destroyEffectPlayer()
я не очень шарю сколько вьюконтроллер живет, но кажется что эффект плеер будет висеть в памяти пока аплик не выгрузишь. предлагаю привязать время жизни эффект плеера к *Appear методам
но если deinit адекватно себя ведет, то может и так пусть будет

2021-02-12 14:43 UTC, bnb-ashershen commented on quickstart-ios-swift/ARCloud/ARCloudViewController.swift
> +    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
наверное чтобы на повортах девайса вызывалось. вопрос снят)

2021-02-12 14:43 UTC, bnb-ashershen approved these changes

2021-02-12 15:47 UTC, GlebPBanuba approved these changes

2021-02-12 15:47 UTC, merged